### ISSUE TITLE
Issues when transpiling typeScript into javaScript

### ISSUE THREAD

**Issue by alepefe95** [vueuse/head#172]
Hello,

I am using vueuse/head in a vite-vue3 project where I mainly use composition API .
Everything works until I transpile the code into javascript.
The static website does not load properly and I get the following error:

Uncaught ReferenceError: can't access lexical declaration 'qg' before initialization.
The error appear when I hover the underlined word in the picture below:
[https://tinypic.host/i/screenshot-from-2022-12-12-06-00-06.RfFfp](https://tinypic.host/i/screenshot-from-2022-12-12-06-00-06.RfFfp)

Code inside main.ts file:
```
import { createHead } from "@vueuse/head"

const app = createApp(App)
app.use(createHead())
```

Code inside the setup function inside component:

```
import { useHead } from "@vueuse/head";

useHead({
    title: 'title'
})
```

Am I doing anything wrong?

Thank you in advance,
Alepefe.

**Comment by harlan-zw** [comment]
Hey @Alepefe 

What you have looks correct. Would it be possible to provide a reproduction?

**Comment by Alepefe** [comment]
Hello @harlan-zw,

I found where the issue comes from.
The rollupOptions inside the vite.config.ts build params:

```
    build: {
      chunkSizeWarningLimit:1500,
      rollupOptions: {
        output: {
          manualChunks(id) {
            if (id.includes('node_modules')) {
              // return id.toString().split('node_modules/')[1].split('/')[0].toString();

              if(id.includes('@vue')){
                return 'vue'

              } else if(id.includes('echarts')) {
                return 'echarts'

              } else if(id.includes('elastic')) {
                return 'elastic'
              }
              
              return 'vendor'
            }
          }
        }
      },
      minify: 'esbuild',
    }
```

**Comment by harlan-zw** [comment]
I'm guessing you mean `useHead`, can you share that code as well?

**Comment by Alepefe** [comment]
@harlan-zw
Yes, I meant in some components, I have to use the useHead() function inside onActivated lifecycle function in order to get the expected behavior.

```
setup(props: any){
    onActivated(()=> {
        useMeta({title: 'title'})
    })
}
```

instead of 
setup(props: any){
    useMeta({title: 'title'})
}

Browse history:
main page (first load) -> contact page (first load) -> main page (cached page so the contact page's meta remains here).

I still don't know why this happens but I suspect it is something related with <keep-alive> directives or <element :key="variable">.

I would not consider this a blocking issue as it does not hamper progress on my project. 
However, this information might be helpful for you.

I will publish further news when I come back to the "meta management" part of my project.

**Comment by Remzi1993** [comment]
@harlan-zw IS this still an issue? I was thinking about using this package in my Vue project?

**Comment by harlan-zw** [comment]
Nuxt uses this library with no issues, I think it depends on your own configuration.
