### ISSUE TITLE
don't recreate `<style>` tags if we're able to dedupe

### ISSUE THREAD

**Issue by danielroe** [vueuse/head#45]
Perhaps use `id`?

context: #44 and https://github.com/nuxt/framework/issues/2337

**Comment by nndnha** [comment]
@egoist I think the problem still exists in case of updating existing attributes.
https://github.com/vueuse/head/blob/5ef9b6225e6c70e18011c33fb77d67de11af0d26/src/index.ts#L137 When do updating element attributes this line will firstly remove them all, so if the  removed attribute is `class` then we will have a flickering screen  as the below example.

```html
<style>
  body.dark {
    background-color: black;
  }
</style>
<body class="dark" data-head-attrs="class">
  ...
</body>
```

**Comment by egoist** [comment]
@nndnha try https://github.com/vueuse/head/releases/tag/v0.7.4 btw nice avatar

**Comment by nndnha** [comment]
@egoist Thanks for your quick fix. It was not easy to describe this problem so here is the real code that I will use it to try to verify the bug. In this demo I will use `MutationObserver` to observe  the changes of the `body` class attribute and show it to the screen. 

https://stackblitz.com/edit/vue-qwpubu?file=public%2Findex.html

The problem comes when we call `useHead` multi times in `App.vue` component.

**Comment by nndnha** [comment]
@egoist Here is the better version  https://codesandbox.io/s/dank-voice-eu4hx?file=/app.vue

We can see that the browser will always received this content by  Nuxt's server side rendering process
```html
<html class="dark" data-head-attrs="class">...
```
And it will make the  whole page dark, after hydration client will firstly remove `html` `class` attribute and then add it again later. This action will make the screen  flickering by toggled  dark/light background color.

**Comment by nndnha** [comment]
@egoist Can you please confirm the bug?

**Comment by KaelWD** [comment]
This is still extremely broken. 

This line removes all link tags that aren't controlled by vueuse/head: https://github.com/vueuse/head/blob/392e8c8ca91df27d9b067dad8c2d9886b53ac756/src/index.ts#L208

If I remove that then this section does the same thing when run by vite-ssg because `querySelector('link[key="null"]')` just returns the first `<link>` due to a jsdom bug:
https://github.com/vueuse/head/blob/392e8c8ca91df27d9b067dad8c2d9886b53ac756/src/index.ts#L213-L218
